name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the server image
        uses: docker/build-push-action@v6
        with:
          context: server
          push: true
          tags: ghcr.io/querateam/docker-ssh-tunnel/server:latest

      - name: Build and push the client image
        uses: docker/build-push-action@v6
        with:
          context: client
          push: true
          tags: ghcr.io/querateam/docker-ssh-tunnel/client:latest
